server:
  port: 8083
spring:
  application:
    name: grssmcrud
  datasource:
    druid:
      url: jdbc:postgresql://postgresdb01.cdd6uaafebcj.ap-northeast-1.rds.amazonaws.com:5432/world
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      max-active: 30
      max-wait: 1500000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: postgresql
    show-sql: true
    open-in-view: false
  output:
    ansi:
      enabled: ALWAYS