server:
  port: 8083
spring:
  application:
    name: grssmcrud
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: oraclect
    password: oraclect
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: world_
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jp.co.toshiba.ppok.entity