server:
  port: 8082
spring:
  application:
    name: grssmcrud
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: oraclect
    password: oraclect
    hikari:
      maximum-pool-size: 30
      max-lifetime: 10000
  output:
    ansi:
      enabled: ALWAYS
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: WORLD_
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
